#cloud-config

# Update and upgrade all packages
package_update: true
package_upgrade: true

disk_setup:
  /dev/sdb:
    layout: true
    overwrite: false

fs_setup:
  - label: data
    device: /dev/sdb
    filesystem: ext4
    overwrite: false

growpart:
  devices: [/dev/sdb]
  mode: auto

mounts:
- [sdb, /data]

packages:
  - curl

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh ./get-docker.sh
  - usermod -a -G docker ubuntu
  - docker compose up -d

write_files:
  - path: /home/ubuntu/caddy/Caddyfile
    owner: ubuntu:ubuntu
    permissions: '0644'
    defer: true
    content: |
      https://${domain_name} {
          reverse_proxy http://immich-server:2283
      }
  - path: /home/ubuntu/docker-compose.yaml
    owner: ubuntu:ubuntu
    permissions: '0644'
    defer: true
    content: |
        ${indent(8, file("${module_path}/files/docker-compose.yml"))}
  - path: /home/ubuntu/.env
    owner: ubuntu:ubuntu
    permissions: '0644'
    defer: true
    content: |
        # You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

        # The location where your uploaded files are stored
        UPLOAD_LOCATION=/data/uploads
        # The location where your database files are stored
        DB_DATA_LOCATION=/data/postgres

        # To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
        # TZ=Etc/UTC

        # The Immich version to use. You can pin this to a specific version like "v1.71.0"
        IMMICH_VERSION=release

        # Connection secret for postgres. You should change it to a random password
        # Please use only the characters `A-Za-z0-9`, without special characters or spaces
        DB_PASSWORD=${postgres_password}

        # The values below this line do not need to be changed
        ###################################################################################
        DB_USERNAME=postgres
        DB_DATABASE_NAME=immich
